# Generated by Django 5.1.6 on 2025-02-09 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('STRENGTH', 'Fuerza/Gimnasio'), ('CARDIO', 'Cardiovascular'), ('HIIT', 'HIIT'), ('MIXED', 'Mixto')], max_length=50, verbose_name='Tipo de entrenamiento')),
                ('difficulty', models.CharField(choices=[('BEG', 'Principiante'), ('INT', 'Intermedio'), ('ADV', 'Avanzado')], max_length=3, verbose_name='Nivel de dificultad')),
                ('exercises', models.JSONField(help_text='Estructura del plan de ejercicios', verbose_name='Ejercicios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Plan activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Plan de entrenamiento',
                'verbose_name_plural': 'Planes de entrenamiento',
                'ordering': ['-created_at'],
            },
        ),
    ]
